Update tutorials for OpenFOAM-7 and enable Alltest in testScript

diff --git a/tutorials/fluidSolidInteraction/microBeamInCrossFlow/Allrun b/tutorials/fluidSolidInteraction/microBeamInCrossFlow/Allrun
--- a/tutorials/fluidSolidInteraction/microBeamInCrossFlow/Allrun
+++ b/tutorials/fluidSolidInteraction/microBeamInCrossFlow/Allrun
@@ -9,6 +9,14 @@ source solids4FoamScripts.sh
 # Check case version is correct
 solids4Foam::convertCaseFormat .
 
+if ! command -v cartesianMesh &> /dev/null
+then
+    echo
+    echo "cartesianMesh command not found, which is required for this case"
+    echo
+    exit 0
+fi
+
 if [[ "${WM_PROJECT}" == "foam" ]]
 then
     # Create solid mesh
